### ISSUE TITLE
Debug walker comparison ec2 run

### ISSUE THREAD

**Issue by cathywu** [cathywu/rllab#5]
Command:
```
python3 examples/cluster_walker_tf_comparison.py
```
An instance was started on EC2 despite the following:
```
Traceback (most recent call last):
  File "examples/cluster_walker_tf_comparison.py", line 99, in <module>
    variant=v,
  File "/Users/cathywu/Dropbox/PhD/DeepRL-Traffic/rllabcathywu/rllab/misc/instrument.py", line 546, in run_experiment_lite
    periodic_sync_interval=periodic_sync_interval)
  File "/Users/cathywu/Dropbox/PhD/DeepRL-Traffic/rllabcathywu/rllab/misc/instrument.py", line 1003, in launch_ec2
    response = ec2.request_spot_instances(**spot_args)
  File "/Users/cathywu/anaconda/envs/rllabcathywu/lib/python3.5/site-packages/botocore/client.py", line 253, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/cathywu/anaconda/envs/rllabcathywu/lib/python3.5/site-packages/botocore/client.py", line 544, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (MaxSpotInstanceCountExceeded) when calling the RequestSpotInstances operation: Max spot instance count exceeded
```
Waiting to see if the instance generates any output.

**Comment by cathywu** [comment]
Woo, output is generated!
![newplot 1](https://cloud.githubusercontent.com/assets/329117/25120730/1bce5350-23d4-11e7-843d-ef6b9693cd4a.png)

We'll see what we have in the morning.
